### ISSUE TITLE
Написать логику начисления очков для пользователей

### ISSUE THREAD

**Issue by SkoblikovAlexey** [SkoblikovAlexey/Football-experts#7]
Написать логику, которая будет сравнивать прогноз пользователя с фактическим результатом и начислять за это очки.
Система начисления очков:
полностью угаданный счёт : 4 очка
угаданный исход и угаданная разница забитых и пропущенных голов - 3 очка
угаданный исход: 2 очка
не угаданный исход: 0 очков.
Программа должна высчитывать очки пользователя после каждого матча ( т.е. когда с оф. сайта РПЛ отпарсится результат  и мы заберем его себе) и добавлять их в базу данных.

**Comment by ademaro** [comment]
Предлагаю начать с функции, надо определить входные параметры и то, что она должна возвращать, жду мыслей, можно прямо тут)

**Comment by SkoblikovAlexey** [comment]
1. Функция на вход принимает два параметра - две строки. Их получаем из БД.  Например: пользователь сделал прогноз на матч и поставил 1:1, в БД в соответствующее поле записывается строка "1:1",  вторую строку так же получаем из БД, куда была записана информация о исходе матча, с помощью парсинга стороннего ресурса, строка того же вида ( например " 2:2").
def calc_points(pred: str fact: str) :
    
2. В теле функции объявляем переменную points =0. После проверяем две строки на равенство. Если они равны, то к points прибавляем 4 очка за полностью угаданный счёт. Если строки не равны, то получаем из каждой два числа. Отдельно для каждой пары   чисел вычисляем  разность: из первого вычитаем второе. Полученный результат записываем в переменную. Далее проверка: если разность первой пары чисел равна разности второй пары, то значит верно угадана разница забитых и пропущенных мячей, к  points прибавляем 3. Если нет, то ещё проверка: если обе разности больше 0 или обе разности меньше ноля, то значит верно угадан исход points+=2. Иначе к points ничего не прибавляем. Возвращаем points. 
3.  Страница results: здесь будет список всех туров чемпионата, при клике на каждый открывается страница данного тура( реализовано с помощью блюпринтов). 
 - на странице тура отображаются матчи тура списком в столбик, справа от названия каждого матча после его завершения будет отображаться его результат, который мы получим путем парсинга официального сайта РПЛ в нашу базу данных. Данную структуру смогут просматривать ВСЕ пользователи (авторизованные и не авторизованные)
 - для авторизованных пользователей, успевших сделать прогнозы до начала матчей тура: рядом с вышеописанным результатом матча будет отображаться их прогноз, а после того, как приложение посчитает очки за прогнозы - и количество очков за каждый конкретный матч. Для авторизованных пользователей, не успевших сделать прогноз на каждый конкретный матч, справа от результата вместо спрогнозированного счета будут прочерки (вида _ : _ ), либо просто пустые строки. 
 - для неавторизованных пользователей на странице results кроме фактических результатов не будет отображаться ничего, кроме предложения авторизоваться для возможности делать прогнозы
 - как опция - можно подкрашивать поля с набранными очками в зависимости от успешности прогноза. 0 очков - красноватый, 2 очка - желтый, 3 очка - светло-зеленый, 4 очка - зеленый
 Схематически должно быть что-то похожее на это: 
![Снимок экрана 2024-02-10 184239](https://github.com/SkoblikovAlexey/Football-experts/assets/110120426/e3e0f212-0f30-492f-90fe-c0cfe8f7cc44)

**Comment by ademaro** [comment]
Нужно подробнее про формат входных строк (с примерами)
